#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: files-checksums-current-directory
## @Creation date file: 27.04.2021, 20:30:55

[[ -z "${files_checksums_current_directory_script_source}" ]] && declare -rx files_checksums_current_directory_script_source="$BASH_SOURCE"

if [[ -z "${files_checksums_current_directory_script_source_path}" ]]; then
    temp_one="$(dirname ${files_checksums_current_directory_script_source})"
    if [[ "${temp_one}" == '.' ]]; then
        declare -rx files_checksums_current_directory_script_source_path="$(pwd)"
    else
        declare -rx files_checksums_current_directory_script_source_path="${temp_one}"
    fi
fi

if [[ -z "${main_run_script_path}" ]]; then
    declare -rx main_run_script_path="$(pwd)"
    printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
    check=1
    while [[ "${check}" -eq 1 ]]; do
        if [[ ! -f 'main.cfg' ]]; then
            if [[ "$(pwd)" != "/" ]]; then
                cd ../
            else
                cd ${main_run_script_path}
                check=0
                echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
                tput sgr0
                exit 1
            fi
        else
            check=0
            declare -rx main_project_path="$(pwd)"
            . "${main_project_path}/main.cfg" "$@"
            cd "${main_run_script_path}"
        fi
    done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

# Как сохранить контрольные суммы файлов в каталоге рекурсивно?
# find -type f \( -not -name 'sha512sum.txt' \) -exec sha512sum '{}' \; >sha512sum.txt

# Как проверить контрольные суммы файлов в каталоге
# sha512sum -c sha512sum.txt >check_results.txt

# Как вывести список не совпадающих с сохранёнными контрольными суммами файлов
# sha512sum -c sha512sum.txt | grep -v 'OK'
# sha512sum -c sha512sum.txt | grep -v 'OK' >failed_results.txt
